### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by alorma** [Softwee/codeview-android#9]
```
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/jetbrains/annotations/NotNull.class
```

After adding your lib, i get this error

https://github.com/gitskarios/Gitskarios/blob/code_view/app/build.gradle#L266

**Comment by kbiakov** [comment]
Hi! Seems like you have dependencies collision. I've just tried to build you project from source, from code-view branch & don't faced with this problem. First of all, try to clean project, otherwise try to resolve collision, for example, using this script:

```groovy
compile (group: 'com.github.softwee', name: 'codeview-android', version: '1.0.3') {
    exclude group: 'org.jetbrains.annotations'
  }
```

As I am guess the problem also may occur when different libraries use common libraries with different versions and this libraries haven't latest versions. Please give your feedback after research.

**Comment by alorma** [comment]
That's weird :S

I've tried cleaning, and also tried your snippet, but it can't compile, even in AS or `./gradlew build`

**Comment by alorma** [comment]
It works!

https://github.com/gitskarios/Gitskarios/commit/9150badd5eb09e87eb207dd9bab7ba7fba29e1af

**Comment by contact2jayu** [comment]
Error comes when sync the project.
Failed to resolve: com.github.kbiakov:CodeView-android:1.3.1
